# Generated by Django 4.0.1 on 2022-02-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('massage', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
