# Generated by Django 4.0.1 on 2022-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.FileField(default=2, upload_to='static'),
            preserve_default=False,
        ),
    ]
