# Generated by Django 4.0.1 on 2022-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.FileField(default=2, upload_to='static'),
            preserve_default=False,
        ),
    ]
