# Generated by Django 4.0.1 on 2022-02-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resform',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='resform',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
