# Generated by Django 4.0.1 on 2022-02-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_first_name_resform_f_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
