# Generated by Django 4.0.1 on 2022-02-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooko', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sliders',
            new_name='Crousal',
        ),
    ]
