# Generated by Django 4.0.1 on 2022-02-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooko', '0002_rename_sliders_crousal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crousal',
        ),
    ]
