# Generated by Django 4.0.1 on 2022-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooko', '0003_delete_crousal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgthree', models.FileField(upload_to='static')),
            ],
        ),
    ]
