# Generated by Django 4.0.1 on 2022-02-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formate', '0002_delete_test_rename_first_name_resform_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resform',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='resform',
            name='l_name',
        ),
        migrations.AddField(
            model_name='resform',
            name='First_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resform',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
